server:
  port: 9001
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password: Lsqlsq123
    lettuce:
      pool:
        max-wait: -1
        max-active: 8
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 100

